version: '3'

volumes:
  data-data:

services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - '.:/code'
    tty: true
    stdin_open: true
    container_name: todo

  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'

  deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "kohei-todo"
    env: "KoheiTodo-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-580481854598"
    bucket_path: "kohei-todo"
    on:
      branch: master
    access_key_id: $AWSAccessKeyId
    secret_access_key:
      secure: $AWSSecretKey